# Generated by Django 2.2.20 on 2021-05-03 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_content', models.CharField(max_length=60)),
                ('source_id', models.CharField(max_length=20)),
                ('source_link', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(blank=True, choices=[('Gus', 'GUS'), ('Slack', 'Slack')], max_length=20, null=True)),
                ('best_answer', models.CharField(blank=True, max_length=60, null=True)),
                ('best_answer_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
