# Generated by Django 3.2 on 2021-05-04 19:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_body', models.CharField(max_length=255)),
                ('source_id', models.CharField(max_length=20)),
                ('source_link', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('Gus', 'GUS'), ('Slack', 'Slack')], max_length=20)),
                ('username', models.CharField(max_length=60)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=20)),
                ('source_link', models.CharField(max_length=255)),
                ('answer_body', models.CharField(max_length=255)),
                ('is_best_answer', models.BooleanField()),
                ('username', models.CharField(max_length=60)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='askme.question')),
            ],
        ),
    ]
